import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - imageprompt",
  description: "Terms of Service for imageprompt. Please read these terms carefully before using our service.",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mt-4 text-xl text-muted-foreground">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="prose prose-gray max-w-none dark:prose-invert">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using imageprompt ("Service"), you accept and agree to be bound by the 
            terms and provision of this agreement. If you do not agree to abide by the above, 
            please do not use this service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            imageprompt provides an AI-powered service that analyzes uploaded images and generates 
            descriptive prompts that can be used with various AI art generation tools. The service 
            is provided "as is" and we reserve the right to modify or discontinue the service at any time.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            To access certain features of the service, you may be required to create an account. 
            You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized use of your account</li>
          </ul>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the service to:</p>
          <ul>
            <li>Upload images that contain illegal, harmful, or inappropriate content</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe upon the rights of others</li>
            <li>Upload images containing copyrighted material without permission</li>
            <li>Use the service for commercial purposes without authorization</li>
            <li>Attempt to reverse engineer or compromise the service</li>
          </ul>

          <h2>5. Content and Intellectual Property</h2>
          <p>
            You retain ownership of the images you upload. By using our service, you grant us a 
            limited license to process your images for the purpose of generating prompts. We do not 
            store your images permanently and they are deleted after processing.
          </p>
          <p>
            The prompts generated by our service are provided for your use, but we make no claims 
            of ownership over the generated content.
          </p>

          <h2>6. Privacy and Data Protection</h2>
          <p>
            Your privacy is important to us. Please review our Privacy Policy to understand how we 
            collect, use, and protect your information.
          </p>

          <h2>7. Service Availability</h2>
          <p>
            We strive to maintain high service availability, but we do not guarantee uninterrupted 
            access to the service. We may suspend or terminate the service for maintenance, updates, 
            or other operational reasons.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            imageprompt and its operators will not be liable for any indirect, incidental, special, 
            consequential, or punitive damages resulting from your use of the service. Our total 
            liability shall not exceed the amount paid by you for the service.
          </p>

          <h2>9. Disclaimer of Warranties</h2>
          <p>
            The service is provided "as is" without warranties of any kind, either express or implied, 
            including but not limited to warranties of merchantability, fitness for a particular 
            purpose, or non-infringement.
          </p>

          <h2>10. Modifications to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will notify users of any 
            significant changes via email or through the service. Continued use of the service 
            after such modifications constitutes acceptance of the updated terms.
          </p>

          <h2>11. Termination</h2>
          <p>
            We may terminate or suspend your account and access to the service immediately, without 
            prior notice, for conduct that we believe violates these terms or is harmful to other 
            users, us, or third parties.
          </p>

          <h2>12. Governing Law</h2>
          <p>
            These terms shall be governed by and construed in accordance with the laws of the 
            jurisdiction in which imageprompt operates, without regard to conflict of law principles.
          </p>

          <h2>13. Contact Information</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at:
            <br />
            Email: <a href="mailto:support@imagepromptgenerator.org" className="text-primary hover:underline">support@imagepromptgenerator.org</a>
          </p>
        </div>
      </div>
    </div>
  );
}